config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :users
  resources :blogs, except: :index

  get 'login' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'users/follow/:id' => 'users#follow'
  post 'users/unfollow/:id' => 'users#unfollow'

  root 'home#index'
  # root 'users#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates_uniqueness_of :follower_id, scope: :followed_id
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :blogs
	validates :username, uniqueness: true
	validates :username, presence: true
	
	has_many :relationships, foreign_key: :follower_id, dependent: :destroy
  	has_many :followers, through: :relationships
  	has_many :followeds, through: :relationships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = User.find(session[:user_id])
    if @blog.save
      flash[:notice] = "New Blog Post! Woop Woop!"
      redirect_to @blog.user
    else
      flash[:alert] = "There was a problem. :("
      redirect_to new_blog_path
    end
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      flash[:notice] = "Blog updated! Yeah!"
      redirect_to @blog.user
    else
      flash[:alert] = "Boo. Something went wrong."
      redirect_to edit_blog_path(@blog)
    end
  end

  def destroy
    if @blog.delete
      flash[:notice] = "Blog go bye bye."
      redirect_to @blog.user
    else
      flash[:alert] = "Hmm. Something weird happened."
      redirect_to :back
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:body)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end

  def delete
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	#check username for existing user
  	@user = User.find_by(username: params[:username] )
  	#if user exists check that password matches
  	if @user
  		if @user.password == params[:password]
  			#if match set session to user_id
  			session[:user_id] = @user.id
  			flash[:notice] = "You have been signed in."
  			redirect_to @user
  		#if no match flash then reroute to login
  		else
  			flash[:alert] = "Password does not match"
  			redirect_to login_path
  		end
  	#if no matching user then flash and reroute to loing 
  	else
  		flash[:alert] = "Username does not exist."
  		redirect_to login_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	flash[:notice] = "You have been logged out."
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow]

  def index
    @users = User.all
  end

  def show
    @users = User.all
  end

  def new
    @user = User.new
    # render layout: "clean"
  end

  def create
    @user = User.create(user_params)
    if @user
      flash[:notice] = "Welcome to your new account!!!."
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:alert] = "There was a problem. Please try again."
      redirect_to new_user_path
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "New user updated."
      redirect_to @user
    else
      flash[:alert] = "There was a problem. Please try again."
      redirect_to user_path(@user)
    end
  end

  def destroy
    if @user.delete
      flash[:notice] = "User deleted."
      redirect_to users_path
    else
      flash[:alert] = "There was a problem"
      redirect_to users_path
    end
  end

  def follow
    @rel = Relationship.create(follower_id: session[:user_id], followed_id: @user.id)
    if @rel
      flash[:notice] = "You just followed #{@user.username}!"
      redirect_to users_path
    else
      flash[:alert] = "That did not go as planned. Sawwy."
      redirect_to users_path
    end
  end

  def unfollow
    @rel = Relationship.find_by(follower_id: session[:user_id], followed_id: @user.id)
    if @rel.delete
      flash[:notice] = "You just unfollowed #{@user.username}!"
      redirect_to users_path
    else
      flash[:alert] = "That did not go as planned. Sawwy."
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :bio, :location)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
def current_user
	session[:user_id].nil? ? nil : User.find(session[:user_id])
end

def current_user2
	session[:user_id] ? User.find(session[:user_id]) : nil
end

def follow_link(current_user, target)
	if current_user
		if current_user == target
		elsif current_user.followeds.include? target
			link_to("Unfollow", "unfollow/#{target.id}", method: "post")
		else
			link_to("Follow", "follow/#{target.id}", method: "post")
		end
	end
end
end

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>
<%= form_for(@blog) do |f| %>
	<%= f.label :body %><br />
	<%= f.text_area :body %><br />
	<%= f.submit :update %>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>
<%= form_for(@blog) do |f| %>
	<%= f.label :body %><br />
	<%= f.text_area :body %><br />
	<%= f.submit :blog %>
<% end %>

app/views/blogs/show.html.erb
<p><%= @blog.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MUMBLER!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="body"></div>
		<div class="grad"></div>
		<div class="header">
			<!-- <div>Site<span>Random</span></div> -->
		</div>
		<br>
<!-- 		<div class="login">
				<input type="text" placeholder="username" name="user"><br>
				<input type="password" placeholder="password" name="password"><br>
				<input type="button" value="Login">
		</div> -->
	<div class="login">
		<%= form_tag('sessions', method: 'post') do %>
			<%= text_field_tag :username, nil, placeholder: "username" %><br />
			<%= password_field_tag :password, nil, placeholder: "password" %><br />
			<%= submit_tag "Login" %>
		<% end %>
	</div>

	<div id="container">
	<nav>
		<% if current_user2 %>
		<p><%= "Welcome #{current_user2.username}" %> | <%= link_to "Logout", logout_path, method: "delete" %></p>
		<% else %>
		<p><%= link_to "Sign in", login_path %> | <%= link_to "Sign up", new_user_path %></p>
		<% end %>
	</nav>
	</div>

    <%= flash[:notice] if flash[:notice] %>
	<%= flash[:alert] if flash[:alert] %>

	<%= yield %>
	
</body>
</html>

app/views/layouts/clean.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clean MUMBLER! </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="container">
	<nav>
		<% if current_user2 %>
		<p><%= "Welcome #{current_user2.username}" %> | <%= link_to "Logout", logout_path, method: "delete" %></p>
		<% else %>
		<p><%= link_to "Sign in", login_path %> | <%= link_to "Sign up", new_user_path %></p>
		<% end %>
	</nav>

	<%= flash[:notice] if flash[:notice] %>
	<%= flash[:alert] if flash[:alert] %>

	<%= yield %>
	</div>
	
</body>
</html>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= form_for(@user) do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %><br />
	<%= f.label :location %>
	<%= f.text_field :location %><br />
	<%= f.label :bio %>
	<%= f.text_area :bio %><br />
	<%= f.label :password %>
	<%= f.password_field :password %><br >
	<%= f.submit :update %>
<% end %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<ul>
	<% @users.each do |user| %>
		<li><%= user.username %> <%= follow_link(current_user, user) %></li>
	<% end %>
</ul>
<br />
<%= link_to "new user", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for(@user) do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %><br />
	<%= f.label :location %>
	<%= f.text_field :location %><br />
	<%= f.label :bio %>
	<%= f.text_area :bio %><br />
	<%= f.label :password %>
	<%= f.password_field :password %><br >
	<%= f.submit :create %>
<% end %>
<br />
<%= link_to "Back", :back %>

app/views/users/show.html.erb
<h3><%= "#{@user.username}'s Profile" %></h3>
<ul>
	<li>Location: <%= @user.location %></li>
	<li>Bio: <%= @user.bio %></li>
</ul>

<h3><%= "#{@user.username}'s Blog Posts" %></h3>
<ul>
	<% @user.blogs.each do |blog| %>
		<li><%= blog.body %> (<%= link_to "Delete Post", blog_path(blog), method: "delete" %>)</li>
	<% end %>
</ul>

<p><%= link_to "New Blog!", new_blog_path %></p>

<h3><%= "#{@user.username}'s Followed Blogs" %></h3>
<ul>
	<% @user.followeds.each do |user| %>
		<li><%= user.username %> <%= follow_link(current_user, user) %></li>
	<% end %>
</ul>